# Generated by Django 5.0.4 on 2024-05-28 21:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_assistant_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_active', models.BooleanField(verbose_name=True)),
            ],
            options={
                'verbose_name': 'Resume_info',
            },
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Assistance'},
        ),
    ]
