# Generated by Django 5.0.4 on 2024-11-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_resume_info_alter_conversation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='is_key_skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='score',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default='Backend developer at NNPC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='Django', max_length=50),
            preserve_default=False,
        ),
    ]
