# Generated by Django 5.0.4 on 2024-11-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_skill_image_remove_skill_is_key_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color_scheme',
            field=models.CharField(choices=[('pink', 'Pink - Beginner'), ('blue', 'Blue - Intermediate'), ('purple', 'Purple - Advanced'), ('green', 'Green - Expert')], default='blue', max_length=20),
        ),
    ]
