# Generated by Django 5.0.4 on 2024-11-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_company_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_key_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='score',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
    ]
