# Generated by Django 5.0.4 on 2024-11-14 15:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='detailed_bio',
            field=ckeditor.fields.RichTextField(help_text='Detailed information shown when expanded'),
        ),
    ]
